CUDA_VISIBLE_DEVICES=1 python scripts/train_tumor_roi.py \
  --medseg_root /home/PuMengYu/medseg_project \
  --preprocessed_root /home/PuMengYu/Task03_Liver_roi \
  --exp_root /home/PuMengYu/experiments/twostage \
  --exp_name focaltversky_smallmine_zoom_p160 \
  --model dynunet \
  --epochs 200 \
  --batch_size 2 \
  --lr 1e-4 \
  --patch 160 160 160 \
  --val_patch 160 160 160 \
  --sw_batch_size 1 \
  --val_every 3 \
  --num_workers 10 \
  --prefetch_factor 4 \
  --amp \
  --loss focaltversky \
  --val_overlap 0.25 \
  --repeats 8 \
  --tumor_ratios 0.1 0.90 \
  --margin 8 \
  --bbox_jitter \
  --bbox_max_shift 8 \
  --random_margin \
  --margin_min 8 \
  --margin_max 20 \
  --use_pred_bbox \
  --small_tumor_thresh 5000 \
  --small_tumor_repeat_scale 4 \
  --no_tumor_repeat_scale 2 \
  --large_tumor_thresh 50000 \
  --large_tumor_repeat_scale 5 \
  --small_tumor_zoom_thresh 5000 \
  --small_tumor_zoom_factor 3.0 \
  --stage1_ckpt /home/PuMengYu/experiments/dynunet_liver_only/train/03-14-01-11-56/best.pt \
  --stage1_patch 144 144 144 \
  --stage1_model dynunet \
  --pred_bbox_cache /home/PuMengYu/Task03_Liver_json/pred_bbox_stage1.json \
  --init_ckpt /home/PuMengYu/experiments/twostage/dynunet_focaltversky_smallmine_zoom_p128/train/04-11-11-53-09/best.pt \
  --seed 42
